removed pnpm

diff --git a/.github/workflows/astro.yml b/.github/workflows/astro.yml
--- a/.github/workflows/astro.yml
+++ b/.github/workflows/astro.yml
@@ -25,19 +25,45 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_ENV
+            echo "command=install" >> $GITHUB_ENV
+            echo "runner=yarn" >> $GITHUB_ENV
+            echo "lockfile=yarn.lock" >> $GITHUB_ENV
+            exit 0
+          elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
+            echo "manager=npm" >> $GITHUB_ENV
+            echo "command=ci" >> $GITHUB_ENV
+            echo "runner=npx --no-install" >> $GITHUB_ENV
+            echo "lockfile=package-lock.json" >> $GITHUB_ENV
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+        shell: /usr/bin/bash -e {0}
+
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: "20"
-          cache: npm
-          cache-dependency-path: package-lock.json
+          cache: ${{ env.manager }}
+          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ env.lockfile }}
+
+      - name: Setup Pages
+        id: pages
+        uses: actions/configure-pages@v5
 
       - name: Install dependencies
-        run: npm ci
+        run: ${{ env.manager }} ${{ env.command }}
         working-directory: ${{ env.BUILD_PATH }}
 
       - name: Build with Astro
-        run: npx astro build
+        run: |
+          ${{ env.runner }} astro build
         working-directory: ${{ env.BUILD_PATH }}
 
       - name: Upload artifact
@@ -56,3 +82,11 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
+
+  notify:
+    runs-on: ubuntu-latest
+    needs: deploy
+    steps:
+      - name: Notify deployment status
+        run: |
+          echo "Deployment complete. Check the GitHub Pages URL: ${{ steps.deployment.outputs.page_url }}"
